env:
  browser: true
  es6: true
  jquery: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-var:
    - error
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
  no-undef:
    - off
  no-console:
    - off
