resolver: lts-14.9

packages:
  - .

allow-newer: false

extra-deps:
  - blank-canvas-0.6.3
  - colour-2.3.4
  - constraints-extras-0.3.0.2
  - dependent-map-0.3
  - dependent-sum-0.6.1
  - kansas-comet-0.4
  - monoidal-containers-0.6
  - ref-tf-0.4.0.2
  - reflex-0.6.2.4
  - witherable-0.3.1
