
resolver: lts-14.9

packages:
  - .

allow-newer: false

extra-deps:
  - ../codeworld-api
  - ../codeworld-error-sanitizer
  - blank-canvas-0.7
  - constraints-extras-0.3.0.2
  - dependent-map-0.3
  - dependent-sum-0.6.1
  - ghc-lib-parser-0.20190909
  - haskell-src-exts-1.21.0
  - kansas-comet-0.4
  - monoidal-containers-0.6
  - ref-tf-0.4.0.2
  - reflex-0.6.2.4
  - witherable-0.3.1
