resolver: lts-14.9
packages:
  - .
allow-newer: false

extra-deps:
  - ../codeworld-account
  - ../codeworld-auth
  - ../codeworld-compiler
  - ../codeworld-error-sanitizer
  - ghc-lib-parser-0.20190909
  - haskell-src-exts-1.20.3
  - hindent-5.3.1
